//SSW-555 Spring 2014 - Team 3

public class ErrorMessage extends Error 
{
	//Format error messages generated by Error
	public ErrorMessage(int lineNum, String msg) 
	{
		super(lineNum, msg);		
	}
	
	public String toString() 
	{
		String s = "Error\t Line  ";
		s += Integer.toString( getLineNumber() );
		s += "\t";
		s += getMessage();
		s += "\n";
				
		return s;
	}
	
}
